name : CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4

     - name: Install Dependencies
       run: pip install pytest pylint

     - name: Run Tests
       run: pytest
       continue-on-error: true

     - name : Run Pylint
       run: pylint calculator.py > pylint report.txt || true
       